### ISSUE TITLE
Can't create an event at 23:00

### ISSUE THREAD

**Issue by myseocompany** [ArrobeFr/jquery-calendar#2]
Hi, i'm new hear. Please excuse my english. 
If I create and event that start at 23:00 or finish at that time, I can not see the event.
My code:
```javascript
            {
              start: moment([2018, 9, 5, 23, 0]).format('X'),
              end:   moment([2018, 9, 5, 23, 0]).add(30,'m').format('X'),
              title: 'title1',
              content: 'content1',
              category:'category1'
            },
           {
              start: moment([2018, 9, 5, 23, 0]).format('X'),
              end:   moment([2018, 9, 5, 23, 0]).add(60,'m').format('X'),
              title: 'title1',
              content: 'content1',
              category:'category1'
            },
```

![Image of MySEO](http://bookme.com.co/images/bug_23_hour.png)

**Comment by LeoVillaretArrobe** [comment]
Thanks for reporting this bug, I will patch this one ASAP.

**Comment by LeoVillaretArrobe** [comment]
The bug was 2 bugs ;
- Estimation of the end of the day is bad
- The condition to display the event is not working well

But the 2 bugs have the same problem : th code is working on hours and not full timestamp, so if the parameter : `weekdey.timeline.intervalMinutes` is not a multiple of 60 (60, 120, 180, ...), it is not working well.

It is patched, I am preparing the release.

**Comment by LeoVillaretArrobe** [comment]
Released. Please use the version 1.0.12
